### ISSUE TITLE
Incorrect Padding error

### ISSUE THREAD

**Issue by jebesen** [Telecogresca/sydres#1]
I try to execute the same code shown as example in the readme and I get a "Incorrect padding" error in the base64.b64decode() function in line 96.

I'm using python3.9 and windows.   Any idea?

**Comment by alexbarcelo** [comment]
The example expects you to put your own `secret_key` there, and it should be a valid Base64 encoded string. This means that it will contain valid characters *and* that it will be properly padded. The readme uses `'123456'` which is **not** a valid Base64 encoded string; valid ones might be like `'123456=='` (properly padded) or `'12345678'` (a length that does not require padding).

However, you should try with your own key (Redsys typically gives a development dummy account for trying things, so of course use that before doing production stuff!).

**Comment by jebesen** [comment]
Wow, so easy. I just didn't realize I had to use my (fake) secret_key.  I will try it again later.

Thanks a lot for your quick response.
